// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateBarGroupRes interface {
	createBarGroupRes()
}

type CreateBarRecordRes interface {
	createBarRecordRes()
}

type CreateBarTimeRangeRes interface {
	createBarTimeRangeRes()
}

type CreateDataSourceRes interface {
	createDataSourceRes()
}

type CreateDividendRes interface {
	createDividendRes()
}

type CreateEntityRes interface {
	createEntityRes()
}

type CreateExchangeRes interface {
	createExchangeRes()
}

type CreateFinancialRes interface {
	createFinancialRes()
}

type CreateIntervalRes interface {
	createIntervalRes()
}

type CreateMarketHoursRes interface {
	createMarketHoursRes()
}

type CreateMarketInfoRes interface {
	createMarketInfoRes()
}

type CreateSplitRes interface {
	createSplitRes()
}

type CreateTradeConditionRes interface {
	createTradeConditionRes()
}

type CreateTradeCorrectionRes interface {
	createTradeCorrectionRes()
}

type CreateTradeRecordRes interface {
	createTradeRecordRes()
}

type CreateTradeTimeRangeRes interface {
	createTradeTimeRangeRes()
}

type DeleteBarGroupRes interface {
	deleteBarGroupRes()
}

type DeleteBarRecordRes interface {
	deleteBarRecordRes()
}

type DeleteBarTimeRangeRes interface {
	deleteBarTimeRangeRes()
}

type DeleteDataSourceRes interface {
	deleteDataSourceRes()
}

type DeleteDividendRes interface {
	deleteDividendRes()
}

type DeleteEntityRes interface {
	deleteEntityRes()
}

type DeleteExchangeRes interface {
	deleteExchangeRes()
}

type DeleteFinancialRes interface {
	deleteFinancialRes()
}

type DeleteIntervalRes interface {
	deleteIntervalRes()
}

type DeleteMarketHoursRes interface {
	deleteMarketHoursRes()
}

type DeleteMarketInfoRes interface {
	deleteMarketInfoRes()
}

type DeleteSplitRes interface {
	deleteSplitRes()
}

type DeleteTradeConditionRes interface {
	deleteTradeConditionRes()
}

type DeleteTradeCorrectionRes interface {
	deleteTradeCorrectionRes()
}

type DeleteTradeRecordRes interface {
	deleteTradeRecordRes()
}

type DeleteTradeTimeRangeRes interface {
	deleteTradeTimeRangeRes()
}

type ListBarGroupRecordsRes interface {
	listBarGroupRecordsRes()
}

type ListBarGroupRes interface {
	listBarGroupRes()
}

type ListBarRecordRes interface {
	listBarRecordRes()
}

type ListBarTimeRangeGroupsRes interface {
	listBarTimeRangeGroupsRes()
}

type ListBarTimeRangeRes interface {
	listBarTimeRangeRes()
}

type ListDataSourceIntervalsRes interface {
	listDataSourceIntervalsRes()
}

type ListDataSourceRes interface {
	listDataSourceRes()
}

type ListDividendRes interface {
	listDividendRes()
}

type ListDividendStockRes interface {
	listDividendStockRes()
}

type ListEntityDividendsRes interface {
	listEntityDividendsRes()
}

type ListEntityExchangesRes interface {
	listEntityExchangesRes()
}

type ListEntityFinancialsRes interface {
	listEntityFinancialsRes()
}

type ListEntityIntervalsRes interface {
	listEntityIntervalsRes()
}

type ListEntityRes interface {
	listEntityRes()
}

type ListEntitySplitsRes interface {
	listEntitySplitsRes()
}

type ListExchangeRes interface {
	listExchangeRes()
}

type ListExchangeStocksRes interface {
	listExchangeStocksRes()
}

type ListFinancialRes interface {
	listFinancialRes()
}

type ListFinancialStockRes interface {
	listFinancialStockRes()
}

type ListIntervalBarsRes interface {
	listIntervalBarsRes()
}

type ListIntervalRes interface {
	listIntervalRes()
}

type ListIntervalTradesRes interface {
	listIntervalTradesRes()
}

type ListMarketHoursRes interface {
	listMarketHoursRes()
}

type ListMarketInfoHoursRes interface {
	listMarketInfoHoursRes()
}

type ListMarketInfoRes interface {
	listMarketInfoRes()
}

type ListSplitRes interface {
	listSplitRes()
}

type ListTradeConditionRecordRes interface {
	listTradeConditionRecordRes()
}

type ListTradeConditionRes interface {
	listTradeConditionRes()
}

type ListTradeCorrectionRecordRes interface {
	listTradeCorrectionRecordRes()
}

type ListTradeCorrectionRes interface {
	listTradeCorrectionRes()
}

type ListTradeRecordConditionsRes interface {
	listTradeRecordConditionsRes()
}

type ListTradeRecordCorrectionRes interface {
	listTradeRecordCorrectionRes()
}

type ListTradeRecordExchangeRes interface {
	listTradeRecordExchangeRes()
}

type ListTradeRecordRes interface {
	listTradeRecordRes()
}

type ListTradeTimeRangeRecordsRes interface {
	listTradeTimeRangeRecordsRes()
}

type ListTradeTimeRangeRes interface {
	listTradeTimeRangeRes()
}

type ReadBarGroupRes interface {
	readBarGroupRes()
}

type ReadBarGroupTimeRangeRes interface {
	readBarGroupTimeRangeRes()
}

type ReadBarRecordGroupRes interface {
	readBarRecordGroupRes()
}

type ReadBarRecordRes interface {
	readBarRecordRes()
}

type ReadBarTimeRangeIntervalRes interface {
	readBarTimeRangeIntervalRes()
}

type ReadBarTimeRangeRes interface {
	readBarTimeRangeRes()
}

type ReadDataSourceRes interface {
	readDataSourceRes()
}

type ReadDividendRes interface {
	readDividendRes()
}

type ReadEntityRes interface {
	readEntityRes()
}

type ReadExchangeRes interface {
	readExchangeRes()
}

type ReadFinancialRes interface {
	readFinancialRes()
}

type ReadIntervalDataSourceRes interface {
	readIntervalDataSourceRes()
}

type ReadIntervalRes interface {
	readIntervalRes()
}

type ReadIntervalStockRes interface {
	readIntervalStockRes()
}

type ReadMarketHoursMarketInfoRes interface {
	readMarketHoursMarketInfoRes()
}

type ReadMarketHoursRes interface {
	readMarketHoursRes()
}

type ReadMarketInfoRes interface {
	readMarketInfoRes()
}

type ReadSplitRes interface {
	readSplitRes()
}

type ReadSplitStockRes interface {
	readSplitStockRes()
}

type ReadTradeConditionRes interface {
	readTradeConditionRes()
}

type ReadTradeCorrectionRes interface {
	readTradeCorrectionRes()
}

type ReadTradeRecordRes interface {
	readTradeRecordRes()
}

type ReadTradeRecordTimeRangeRes interface {
	readTradeRecordTimeRangeRes()
}

type ReadTradeTimeRangeIntervalRes interface {
	readTradeTimeRangeIntervalRes()
}

type ReadTradeTimeRangeRes interface {
	readTradeTimeRangeRes()
}

type UpdateBarGroupRes interface {
	updateBarGroupRes()
}

type UpdateBarRecordRes interface {
	updateBarRecordRes()
}

type UpdateBarTimeRangeRes interface {
	updateBarTimeRangeRes()
}

type UpdateDataSourceRes interface {
	updateDataSourceRes()
}

type UpdateDividendRes interface {
	updateDividendRes()
}

type UpdateEntityRes interface {
	updateEntityRes()
}

type UpdateExchangeRes interface {
	updateExchangeRes()
}

type UpdateFinancialRes interface {
	updateFinancialRes()
}

type UpdateIntervalRes interface {
	updateIntervalRes()
}

type UpdateMarketHoursRes interface {
	updateMarketHoursRes()
}

type UpdateMarketInfoRes interface {
	updateMarketInfoRes()
}

type UpdateSplitRes interface {
	updateSplitRes()
}

type UpdateTradeConditionRes interface {
	updateTradeConditionRes()
}

type UpdateTradeCorrectionRes interface {
	updateTradeCorrectionRes()
}

type UpdateTradeRecordRes interface {
	updateTradeRecordRes()
}

type UpdateTradeTimeRangeRes interface {
	updateTradeTimeRangeRes()
}
