// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nathanhack/sibyl/ent/bargroup"
	"github.com/nathanhack/sibyl/ent/predicate"
)

// BarGroupDelete is the builder for deleting a BarGroup entity.
type BarGroupDelete struct {
	config
	hooks    []Hook
	mutation *BarGroupMutation
}

// Where appends a list predicates to the BarGroupDelete builder.
func (bgd *BarGroupDelete) Where(ps ...predicate.BarGroup) *BarGroupDelete {
	bgd.mutation.Where(ps...)
	return bgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bgd *BarGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, BarGroupMutation](ctx, bgd.sqlExec, bgd.mutation, bgd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bgd *BarGroupDelete) ExecX(ctx context.Context) int {
	n, err := bgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bgd *BarGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: bargroup.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bargroup.FieldID,
			},
		},
	}
	if ps := bgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bgd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bgd.mutation.done = true
	return affected, err
}

// BarGroupDeleteOne is the builder for deleting a single BarGroup entity.
type BarGroupDeleteOne struct {
	bgd *BarGroupDelete
}

// Exec executes the deletion query.
func (bgdo *BarGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := bgdo.bgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bargroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bgdo *BarGroupDeleteOne) ExecX(ctx context.Context) {
	bgdo.bgd.ExecX(ctx)
}
