// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nathanhack/sibyl/ent/bargroup"
	"github.com/nathanhack/sibyl/ent/barrecord"
	"github.com/nathanhack/sibyl/ent/bartimerange"
	"github.com/nathanhack/sibyl/ent/predicate"
)

// BarGroupQuery is the builder for querying BarGroup entities.
type BarGroupQuery struct {
	config
	ctx           *QueryContext
	order         []bargroup.OrderOption
	inters        []Interceptor
	predicates    []predicate.BarGroup
	withTimeRange *BarTimeRangeQuery
	withRecords   *BarRecordQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BarGroupQuery builder.
func (bgq *BarGroupQuery) Where(ps ...predicate.BarGroup) *BarGroupQuery {
	bgq.predicates = append(bgq.predicates, ps...)
	return bgq
}

// Limit the number of records to be returned by this query.
func (bgq *BarGroupQuery) Limit(limit int) *BarGroupQuery {
	bgq.ctx.Limit = &limit
	return bgq
}

// Offset to start from.
func (bgq *BarGroupQuery) Offset(offset int) *BarGroupQuery {
	bgq.ctx.Offset = &offset
	return bgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bgq *BarGroupQuery) Unique(unique bool) *BarGroupQuery {
	bgq.ctx.Unique = &unique
	return bgq
}

// Order specifies how the records should be ordered.
func (bgq *BarGroupQuery) Order(o ...bargroup.OrderOption) *BarGroupQuery {
	bgq.order = append(bgq.order, o...)
	return bgq
}

// QueryTimeRange chains the current query on the "time_range" edge.
func (bgq *BarGroupQuery) QueryTimeRange() *BarTimeRangeQuery {
	query := (&BarTimeRangeClient{config: bgq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bargroup.Table, bargroup.FieldID, selector),
			sqlgraph.To(bartimerange.Table, bartimerange.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, bargroup.TimeRangeTable, bargroup.TimeRangeColumn),
		)
		fromU = sqlgraph.SetNeighbors(bgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRecords chains the current query on the "records" edge.
func (bgq *BarGroupQuery) QueryRecords() *BarRecordQuery {
	query := (&BarRecordClient{config: bgq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bargroup.Table, bargroup.FieldID, selector),
			sqlgraph.To(barrecord.Table, barrecord.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bargroup.RecordsTable, bargroup.RecordsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BarGroup entity from the query.
// Returns a *NotFoundError when no BarGroup was found.
func (bgq *BarGroupQuery) First(ctx context.Context) (*BarGroup, error) {
	nodes, err := bgq.Limit(1).All(setContextOp(ctx, bgq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bargroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bgq *BarGroupQuery) FirstX(ctx context.Context) *BarGroup {
	node, err := bgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BarGroup ID from the query.
// Returns a *NotFoundError when no BarGroup ID was found.
func (bgq *BarGroupQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bgq.Limit(1).IDs(setContextOp(ctx, bgq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bargroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bgq *BarGroupQuery) FirstIDX(ctx context.Context) int {
	id, err := bgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BarGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BarGroup entity is found.
// Returns a *NotFoundError when no BarGroup entities are found.
func (bgq *BarGroupQuery) Only(ctx context.Context) (*BarGroup, error) {
	nodes, err := bgq.Limit(2).All(setContextOp(ctx, bgq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bargroup.Label}
	default:
		return nil, &NotSingularError{bargroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bgq *BarGroupQuery) OnlyX(ctx context.Context) *BarGroup {
	node, err := bgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BarGroup ID in the query.
// Returns a *NotSingularError when more than one BarGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (bgq *BarGroupQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bgq.Limit(2).IDs(setContextOp(ctx, bgq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bargroup.Label}
	default:
		err = &NotSingularError{bargroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bgq *BarGroupQuery) OnlyIDX(ctx context.Context) int {
	id, err := bgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BarGroups.
func (bgq *BarGroupQuery) All(ctx context.Context) ([]*BarGroup, error) {
	ctx = setContextOp(ctx, bgq.ctx, ent.OpQueryAll)
	if err := bgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BarGroup, *BarGroupQuery]()
	return withInterceptors[[]*BarGroup](ctx, bgq, qr, bgq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bgq *BarGroupQuery) AllX(ctx context.Context) []*BarGroup {
	nodes, err := bgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BarGroup IDs.
func (bgq *BarGroupQuery) IDs(ctx context.Context) (ids []int, err error) {
	if bgq.ctx.Unique == nil && bgq.path != nil {
		bgq.Unique(true)
	}
	ctx = setContextOp(ctx, bgq.ctx, ent.OpQueryIDs)
	if err = bgq.Select(bargroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bgq *BarGroupQuery) IDsX(ctx context.Context) []int {
	ids, err := bgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bgq *BarGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bgq.ctx, ent.OpQueryCount)
	if err := bgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bgq, querierCount[*BarGroupQuery](), bgq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bgq *BarGroupQuery) CountX(ctx context.Context) int {
	count, err := bgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bgq *BarGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bgq.ctx, ent.OpQueryExist)
	switch _, err := bgq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bgq *BarGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := bgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BarGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bgq *BarGroupQuery) Clone() *BarGroupQuery {
	if bgq == nil {
		return nil
	}
	return &BarGroupQuery{
		config:        bgq.config,
		ctx:           bgq.ctx.Clone(),
		order:         append([]bargroup.OrderOption{}, bgq.order...),
		inters:        append([]Interceptor{}, bgq.inters...),
		predicates:    append([]predicate.BarGroup{}, bgq.predicates...),
		withTimeRange: bgq.withTimeRange.Clone(),
		withRecords:   bgq.withRecords.Clone(),
		// clone intermediate query.
		sql:  bgq.sql.Clone(),
		path: bgq.path,
	}
}

// WithTimeRange tells the query-builder to eager-load the nodes that are connected to
// the "time_range" edge. The optional arguments are used to configure the query builder of the edge.
func (bgq *BarGroupQuery) WithTimeRange(opts ...func(*BarTimeRangeQuery)) *BarGroupQuery {
	query := (&BarTimeRangeClient{config: bgq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bgq.withTimeRange = query
	return bgq
}

// WithRecords tells the query-builder to eager-load the nodes that are connected to
// the "records" edge. The optional arguments are used to configure the query builder of the edge.
func (bgq *BarGroupQuery) WithRecords(opts ...func(*BarRecordQuery)) *BarGroupQuery {
	query := (&BarRecordClient{config: bgq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bgq.withRecords = query
	return bgq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		First time.Time `json:"first,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BarGroup.Query().
//		GroupBy(bargroup.FieldFirst).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bgq *BarGroupQuery) GroupBy(field string, fields ...string) *BarGroupGroupBy {
	bgq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BarGroupGroupBy{build: bgq}
	grbuild.flds = &bgq.ctx.Fields
	grbuild.label = bargroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		First time.Time `json:"first,omitempty"`
//	}
//
//	client.BarGroup.Query().
//		Select(bargroup.FieldFirst).
//		Scan(ctx, &v)
func (bgq *BarGroupQuery) Select(fields ...string) *BarGroupSelect {
	bgq.ctx.Fields = append(bgq.ctx.Fields, fields...)
	sbuild := &BarGroupSelect{BarGroupQuery: bgq}
	sbuild.label = bargroup.Label
	sbuild.flds, sbuild.scan = &bgq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BarGroupSelect configured with the given aggregations.
func (bgq *BarGroupQuery) Aggregate(fns ...AggregateFunc) *BarGroupSelect {
	return bgq.Select().Aggregate(fns...)
}

func (bgq *BarGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bgq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bgq); err != nil {
				return err
			}
		}
	}
	for _, f := range bgq.ctx.Fields {
		if !bargroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bgq.path != nil {
		prev, err := bgq.path(ctx)
		if err != nil {
			return err
		}
		bgq.sql = prev
	}
	return nil
}

func (bgq *BarGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BarGroup, error) {
	var (
		nodes       = []*BarGroup{}
		_spec       = bgq.querySpec()
		loadedTypes = [2]bool{
			bgq.withTimeRange != nil,
			bgq.withRecords != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BarGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BarGroup{config: bgq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bgq.withTimeRange; query != nil {
		if err := bgq.loadTimeRange(ctx, query, nodes, nil,
			func(n *BarGroup, e *BarTimeRange) { n.Edges.TimeRange = e }); err != nil {
			return nil, err
		}
	}
	if query := bgq.withRecords; query != nil {
		if err := bgq.loadRecords(ctx, query, nodes,
			func(n *BarGroup) { n.Edges.Records = []*BarRecord{} },
			func(n *BarGroup, e *BarRecord) { n.Edges.Records = append(n.Edges.Records, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bgq *BarGroupQuery) loadTimeRange(ctx context.Context, query *BarTimeRangeQuery, nodes []*BarGroup, init func(*BarGroup), assign func(*BarGroup, *BarTimeRange)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*BarGroup)
	for i := range nodes {
		fk := nodes[i].TimeRangeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(bartimerange.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "time_range_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (bgq *BarGroupQuery) loadRecords(ctx context.Context, query *BarRecordQuery, nodes []*BarGroup, init func(*BarGroup), assign func(*BarGroup, *BarRecord)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*BarGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.BarRecord(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(bargroup.RecordsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.bar_group_records
		if fk == nil {
			return fmt.Errorf(`foreign-key "bar_group_records" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "bar_group_records" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (bgq *BarGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bgq.querySpec()
	_spec.Node.Columns = bgq.ctx.Fields
	if len(bgq.ctx.Fields) > 0 {
		_spec.Unique = bgq.ctx.Unique != nil && *bgq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bgq.driver, _spec)
}

func (bgq *BarGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(bargroup.Table, bargroup.Columns, sqlgraph.NewFieldSpec(bargroup.FieldID, field.TypeInt))
	_spec.From = bgq.sql
	if unique := bgq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bgq.path != nil {
		_spec.Unique = true
	}
	if fields := bgq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bargroup.FieldID)
		for i := range fields {
			if fields[i] != bargroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if bgq.withTimeRange != nil {
			_spec.Node.AddColumnOnce(bargroup.FieldTimeRangeID)
		}
	}
	if ps := bgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bgq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bgq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bgq *BarGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bgq.driver.Dialect())
	t1 := builder.Table(bargroup.Table)
	columns := bgq.ctx.Fields
	if len(columns) == 0 {
		columns = bargroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bgq.sql != nil {
		selector = bgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bgq.ctx.Unique != nil && *bgq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bgq.predicates {
		p(selector)
	}
	for _, p := range bgq.order {
		p(selector)
	}
	if offset := bgq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bgq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BarGroupGroupBy is the group-by builder for BarGroup entities.
type BarGroupGroupBy struct {
	selector
	build *BarGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bggb *BarGroupGroupBy) Aggregate(fns ...AggregateFunc) *BarGroupGroupBy {
	bggb.fns = append(bggb.fns, fns...)
	return bggb
}

// Scan applies the selector query and scans the result into the given value.
func (bggb *BarGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bggb.build.ctx, ent.OpQueryGroupBy)
	if err := bggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BarGroupQuery, *BarGroupGroupBy](ctx, bggb.build, bggb, bggb.build.inters, v)
}

func (bggb *BarGroupGroupBy) sqlScan(ctx context.Context, root *BarGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bggb.fns))
	for _, fn := range bggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bggb.flds)+len(bggb.fns))
		for _, f := range *bggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BarGroupSelect is the builder for selecting fields of BarGroup entities.
type BarGroupSelect struct {
	*BarGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bgs *BarGroupSelect) Aggregate(fns ...AggregateFunc) *BarGroupSelect {
	bgs.fns = append(bgs.fns, fns...)
	return bgs
}

// Scan applies the selector query and scans the result into the given value.
func (bgs *BarGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgs.ctx, ent.OpQuerySelect)
	if err := bgs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BarGroupQuery, *BarGroupSelect](ctx, bgs.BarGroupQuery, bgs, bgs.inters, v)
}

func (bgs *BarGroupSelect) sqlScan(ctx context.Context, root *BarGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bgs.fns))
	for _, fn := range bgs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bgs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
