// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nathanhack/sibyl/ent/interval"
	"github.com/nathanhack/sibyl/ent/predicate"
)

// IntervalDelete is the builder for deleting a Interval entity.
type IntervalDelete struct {
	config
	hooks    []Hook
	mutation *IntervalMutation
}

// Where appends a list predicates to the IntervalDelete builder.
func (id *IntervalDelete) Where(ps ...predicate.Interval) *IntervalDelete {
	id.mutation.Where(ps...)
	return id
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (id *IntervalDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, IntervalMutation](ctx, id.sqlExec, id.mutation, id.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (id *IntervalDelete) ExecX(ctx context.Context) int {
	n, err := id.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (id *IntervalDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: interval.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: interval.FieldID,
			},
		},
	}
	if ps := id.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, id.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	id.mutation.done = true
	return affected, err
}

// IntervalDeleteOne is the builder for deleting a single Interval entity.
type IntervalDeleteOne struct {
	id *IntervalDelete
}

// Exec executes the deletion query.
func (ido *IntervalDeleteOne) Exec(ctx context.Context) error {
	n, err := ido.id.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{interval.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ido *IntervalDeleteOne) ExecX(ctx context.Context) {
	ido.id.ExecX(ctx)
}
