// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nathanhack/sibyl/ent/predicate"
	"github.com/nathanhack/sibyl/ent/tradecondition"
	"github.com/nathanhack/sibyl/ent/traderecord"
)

// TradeConditionQuery is the builder for querying TradeCondition entities.
type TradeConditionQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	inters     []Interceptor
	predicates []predicate.TradeCondition
	withRecord *TradeRecordQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TradeConditionQuery builder.
func (tcq *TradeConditionQuery) Where(ps ...predicate.TradeCondition) *TradeConditionQuery {
	tcq.predicates = append(tcq.predicates, ps...)
	return tcq
}

// Limit the number of records to be returned by this query.
func (tcq *TradeConditionQuery) Limit(limit int) *TradeConditionQuery {
	tcq.limit = &limit
	return tcq
}

// Offset to start from.
func (tcq *TradeConditionQuery) Offset(offset int) *TradeConditionQuery {
	tcq.offset = &offset
	return tcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tcq *TradeConditionQuery) Unique(unique bool) *TradeConditionQuery {
	tcq.unique = &unique
	return tcq
}

// Order specifies how the records should be ordered.
func (tcq *TradeConditionQuery) Order(o ...OrderFunc) *TradeConditionQuery {
	tcq.order = append(tcq.order, o...)
	return tcq
}

// QueryRecord chains the current query on the "record" edge.
func (tcq *TradeConditionQuery) QueryRecord() *TradeRecordQuery {
	query := (&TradeRecordClient{config: tcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tradecondition.Table, tradecondition.FieldID, selector),
			sqlgraph.To(traderecord.Table, traderecord.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, tradecondition.RecordTable, tradecondition.RecordPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(tcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TradeCondition entity from the query.
// Returns a *NotFoundError when no TradeCondition was found.
func (tcq *TradeConditionQuery) First(ctx context.Context) (*TradeCondition, error) {
	nodes, err := tcq.Limit(1).All(newQueryContext(ctx, TypeTradeCondition, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tradecondition.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tcq *TradeConditionQuery) FirstX(ctx context.Context) *TradeCondition {
	node, err := tcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TradeCondition ID from the query.
// Returns a *NotFoundError when no TradeCondition ID was found.
func (tcq *TradeConditionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tcq.Limit(1).IDs(newQueryContext(ctx, TypeTradeCondition, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tradecondition.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tcq *TradeConditionQuery) FirstIDX(ctx context.Context) int {
	id, err := tcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TradeCondition entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TradeCondition entity is found.
// Returns a *NotFoundError when no TradeCondition entities are found.
func (tcq *TradeConditionQuery) Only(ctx context.Context) (*TradeCondition, error) {
	nodes, err := tcq.Limit(2).All(newQueryContext(ctx, TypeTradeCondition, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tradecondition.Label}
	default:
		return nil, &NotSingularError{tradecondition.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tcq *TradeConditionQuery) OnlyX(ctx context.Context) *TradeCondition {
	node, err := tcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TradeCondition ID in the query.
// Returns a *NotSingularError when more than one TradeCondition ID is found.
// Returns a *NotFoundError when no entities are found.
func (tcq *TradeConditionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tcq.Limit(2).IDs(newQueryContext(ctx, TypeTradeCondition, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tradecondition.Label}
	default:
		err = &NotSingularError{tradecondition.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tcq *TradeConditionQuery) OnlyIDX(ctx context.Context) int {
	id, err := tcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TradeConditions.
func (tcq *TradeConditionQuery) All(ctx context.Context) ([]*TradeCondition, error) {
	ctx = newQueryContext(ctx, TypeTradeCondition, "All")
	if err := tcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TradeCondition, *TradeConditionQuery]()
	return withInterceptors[[]*TradeCondition](ctx, tcq, qr, tcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tcq *TradeConditionQuery) AllX(ctx context.Context) []*TradeCondition {
	nodes, err := tcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TradeCondition IDs.
func (tcq *TradeConditionQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = newQueryContext(ctx, TypeTradeCondition, "IDs")
	if err := tcq.Select(tradecondition.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tcq *TradeConditionQuery) IDsX(ctx context.Context) []int {
	ids, err := tcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tcq *TradeConditionQuery) Count(ctx context.Context) (int, error) {
	ctx = newQueryContext(ctx, TypeTradeCondition, "Count")
	if err := tcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tcq, querierCount[*TradeConditionQuery](), tcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tcq *TradeConditionQuery) CountX(ctx context.Context) int {
	count, err := tcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tcq *TradeConditionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = newQueryContext(ctx, TypeTradeCondition, "Exist")
	switch _, err := tcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tcq *TradeConditionQuery) ExistX(ctx context.Context) bool {
	exist, err := tcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TradeConditionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tcq *TradeConditionQuery) Clone() *TradeConditionQuery {
	if tcq == nil {
		return nil
	}
	return &TradeConditionQuery{
		config:     tcq.config,
		limit:      tcq.limit,
		offset:     tcq.offset,
		order:      append([]OrderFunc{}, tcq.order...),
		inters:     append([]Interceptor{}, tcq.inters...),
		predicates: append([]predicate.TradeCondition{}, tcq.predicates...),
		withRecord: tcq.withRecord.Clone(),
		// clone intermediate query.
		sql:    tcq.sql.Clone(),
		path:   tcq.path,
		unique: tcq.unique,
	}
}

// WithRecord tells the query-builder to eager-load the nodes that are connected to
// the "record" edge. The optional arguments are used to configure the query builder of the edge.
func (tcq *TradeConditionQuery) WithRecord(opts ...func(*TradeRecordQuery)) *TradeConditionQuery {
	query := (&TradeRecordClient{config: tcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tcq.withRecord = query
	return tcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Condition string `json:"condition,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TradeCondition.Query().
//		GroupBy(tradecondition.FieldCondition).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tcq *TradeConditionQuery) GroupBy(field string, fields ...string) *TradeConditionGroupBy {
	tcq.fields = append([]string{field}, fields...)
	grbuild := &TradeConditionGroupBy{build: tcq}
	grbuild.flds = &tcq.fields
	grbuild.label = tradecondition.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Condition string `json:"condition,omitempty"`
//	}
//
//	client.TradeCondition.Query().
//		Select(tradecondition.FieldCondition).
//		Scan(ctx, &v)
func (tcq *TradeConditionQuery) Select(fields ...string) *TradeConditionSelect {
	tcq.fields = append(tcq.fields, fields...)
	sbuild := &TradeConditionSelect{TradeConditionQuery: tcq}
	sbuild.label = tradecondition.Label
	sbuild.flds, sbuild.scan = &tcq.fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TradeConditionSelect configured with the given aggregations.
func (tcq *TradeConditionQuery) Aggregate(fns ...AggregateFunc) *TradeConditionSelect {
	return tcq.Select().Aggregate(fns...)
}

func (tcq *TradeConditionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tcq); err != nil {
				return err
			}
		}
	}
	for _, f := range tcq.fields {
		if !tradecondition.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tcq.path != nil {
		prev, err := tcq.path(ctx)
		if err != nil {
			return err
		}
		tcq.sql = prev
	}
	return nil
}

func (tcq *TradeConditionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TradeCondition, error) {
	var (
		nodes       = []*TradeCondition{}
		_spec       = tcq.querySpec()
		loadedTypes = [1]bool{
			tcq.withRecord != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TradeCondition).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TradeCondition{config: tcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tcq.withRecord; query != nil {
		if err := tcq.loadRecord(ctx, query, nodes,
			func(n *TradeCondition) { n.Edges.Record = []*TradeRecord{} },
			func(n *TradeCondition, e *TradeRecord) { n.Edges.Record = append(n.Edges.Record, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tcq *TradeConditionQuery) loadRecord(ctx context.Context, query *TradeRecordQuery, nodes []*TradeCondition, init func(*TradeCondition), assign func(*TradeCondition, *TradeRecord)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*TradeCondition)
	nids := make(map[int]map[*TradeCondition]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(tradecondition.RecordTable)
		s.Join(joinT).On(s.C(traderecord.FieldID), joinT.C(tradecondition.RecordPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(tradecondition.RecordPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(tradecondition.RecordPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*TradeCondition]struct{}{byID[outValue]: {}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "record" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (tcq *TradeConditionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tcq.querySpec()
	_spec.Node.Columns = tcq.fields
	if len(tcq.fields) > 0 {
		_spec.Unique = tcq.unique != nil && *tcq.unique
	}
	return sqlgraph.CountNodes(ctx, tcq.driver, _spec)
}

func (tcq *TradeConditionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tradecondition.Table,
			Columns: tradecondition.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tradecondition.FieldID,
			},
		},
		From:   tcq.sql,
		Unique: true,
	}
	if unique := tcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tradecondition.FieldID)
		for i := range fields {
			if fields[i] != tradecondition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tcq *TradeConditionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tcq.driver.Dialect())
	t1 := builder.Table(tradecondition.Table)
	columns := tcq.fields
	if len(columns) == 0 {
		columns = tradecondition.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tcq.sql != nil {
		selector = tcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tcq.unique != nil && *tcq.unique {
		selector.Distinct()
	}
	for _, p := range tcq.predicates {
		p(selector)
	}
	for _, p := range tcq.order {
		p(selector)
	}
	if offset := tcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TradeConditionGroupBy is the group-by builder for TradeCondition entities.
type TradeConditionGroupBy struct {
	selector
	build *TradeConditionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tcgb *TradeConditionGroupBy) Aggregate(fns ...AggregateFunc) *TradeConditionGroupBy {
	tcgb.fns = append(tcgb.fns, fns...)
	return tcgb
}

// Scan applies the selector query and scans the result into the given value.
func (tcgb *TradeConditionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeTradeCondition, "GroupBy")
	if err := tcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TradeConditionQuery, *TradeConditionGroupBy](ctx, tcgb.build, tcgb, tcgb.build.inters, v)
}

func (tcgb *TradeConditionGroupBy) sqlScan(ctx context.Context, root *TradeConditionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tcgb.fns))
	for _, fn := range tcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tcgb.flds)+len(tcgb.fns))
		for _, f := range *tcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TradeConditionSelect is the builder for selecting fields of TradeCondition entities.
type TradeConditionSelect struct {
	*TradeConditionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tcs *TradeConditionSelect) Aggregate(fns ...AggregateFunc) *TradeConditionSelect {
	tcs.fns = append(tcs.fns, fns...)
	return tcs
}

// Scan applies the selector query and scans the result into the given value.
func (tcs *TradeConditionSelect) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeTradeCondition, "Select")
	if err := tcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TradeConditionQuery, *TradeConditionSelect](ctx, tcs.TradeConditionQuery, tcs, tcs.inters, v)
}

func (tcs *TradeConditionSelect) sqlScan(ctx context.Context, root *TradeConditionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tcs.fns))
	for _, fn := range tcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
