// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nathanhack/sibyl/ent/predicate"
	"github.com/nathanhack/sibyl/ent/traderecord"
)

// TradeRecordDelete is the builder for deleting a TradeRecord entity.
type TradeRecordDelete struct {
	config
	hooks    []Hook
	mutation *TradeRecordMutation
}

// Where appends a list predicates to the TradeRecordDelete builder.
func (trd *TradeRecordDelete) Where(ps ...predicate.TradeRecord) *TradeRecordDelete {
	trd.mutation.Where(ps...)
	return trd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (trd *TradeRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, TradeRecordMutation](ctx, trd.sqlExec, trd.mutation, trd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (trd *TradeRecordDelete) ExecX(ctx context.Context) int {
	n, err := trd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (trd *TradeRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: traderecord.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: traderecord.FieldID,
			},
		},
	}
	if ps := trd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, trd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	trd.mutation.done = true
	return affected, err
}

// TradeRecordDeleteOne is the builder for deleting a single TradeRecord entity.
type TradeRecordDeleteOne struct {
	trd *TradeRecordDelete
}

// Exec executes the deletion query.
func (trdo *TradeRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := trdo.trd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{traderecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (trdo *TradeRecordDeleteOne) ExecX(ctx context.Context) {
	trdo.trd.ExecX(ctx)
}
