// Code generated by ent, DO NOT EDIT.

package entity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the entity type in the database.
	Label = "entity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldTicker holds the string denoting the ticker field in the database.
	FieldTicker = "ticker"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldListDate holds the string denoting the list_date field in the database.
	FieldListDate = "list_date"
	// FieldOptions holds the string denoting the options field in the database.
	FieldOptions = "options"
	// FieldTradable holds the string denoting the tradable field in the database.
	FieldTradable = "tradable"
	// EdgeExchanges holds the string denoting the exchanges edge name in mutations.
	EdgeExchanges = "exchanges"
	// EdgeIntervals holds the string denoting the intervals edge name in mutations.
	EdgeIntervals = "intervals"
	// EdgeDividends holds the string denoting the dividends edge name in mutations.
	EdgeDividends = "dividends"
	// EdgeSplits holds the string denoting the splits edge name in mutations.
	EdgeSplits = "splits"
	// EdgeFinancials holds the string denoting the financials edge name in mutations.
	EdgeFinancials = "financials"
	// Table holds the table name of the entity in the database.
	Table = "entities"
	// ExchangesTable is the table that holds the exchanges relation/edge. The primary key declared below.
	ExchangesTable = "entity_exchanges"
	// ExchangesInverseTable is the table name for the Exchange entity.
	// It exists in this package in order to avoid circular dependency with the "exchange" package.
	ExchangesInverseTable = "exchanges"
	// IntervalsTable is the table that holds the intervals relation/edge.
	IntervalsTable = "intervals"
	// IntervalsInverseTable is the table name for the Interval entity.
	// It exists in this package in order to avoid circular dependency with the "interval" package.
	IntervalsInverseTable = "intervals"
	// IntervalsColumn is the table column denoting the intervals relation/edge.
	IntervalsColumn = "stock_id"
	// DividendsTable is the table that holds the dividends relation/edge. The primary key declared below.
	DividendsTable = "entity_dividends"
	// DividendsInverseTable is the table name for the Dividend entity.
	// It exists in this package in order to avoid circular dependency with the "dividend" package.
	DividendsInverseTable = "dividends"
	// SplitsTable is the table that holds the splits relation/edge.
	SplitsTable = "splits"
	// SplitsInverseTable is the table name for the Split entity.
	// It exists in this package in order to avoid circular dependency with the "split" package.
	SplitsInverseTable = "splits"
	// SplitsColumn is the table column denoting the splits relation/edge.
	SplitsColumn = "entity_splits"
	// FinancialsTable is the table that holds the financials relation/edge. The primary key declared below.
	FinancialsTable = "entity_financials"
	// FinancialsInverseTable is the table name for the Financial entity.
	// It exists in this package in order to avoid circular dependency with the "financial" package.
	FinancialsInverseTable = "financials"
)

// Columns holds all SQL columns for entity fields.
var Columns = []string{
	FieldID,
	FieldActive,
	FieldTicker,
	FieldName,
	FieldDescription,
	FieldListDate,
	FieldOptions,
	FieldTradable,
}

var (
	// ExchangesPrimaryKey and ExchangesColumn2 are the table columns denoting the
	// primary key for the exchanges relation (M2M).
	ExchangesPrimaryKey = []string{"entity_id", "exchange_id"}
	// DividendsPrimaryKey and DividendsColumn2 are the table columns denoting the
	// primary key for the dividends relation (M2M).
	DividendsPrimaryKey = []string{"entity_id", "dividend_id"}
	// FinancialsPrimaryKey and FinancialsColumn2 are the table columns denoting the
	// primary key for the financials relation (M2M).
	FinancialsPrimaryKey = []string{"entity_id", "financial_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TickerValidator is a validator for the "ticker" field. It is called by the builders before save.
	TickerValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultListDate holds the default value on creation for the "list_date" field.
	DefaultListDate time.Time
)

// OrderOption defines the ordering options for the Entity queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByTicker orders the results by the ticker field.
func ByTicker(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicker, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByListDate orders the results by the list_date field.
func ByListDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldListDate, opts...).ToFunc()
}

// ByOptions orders the results by the options field.
func ByOptions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOptions, opts...).ToFunc()
}

// ByTradable orders the results by the tradable field.
func ByTradable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTradable, opts...).ToFunc()
}

// ByExchangesCount orders the results by exchanges count.
func ByExchangesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExchangesStep(), opts...)
	}
}

// ByExchanges orders the results by exchanges terms.
func ByExchanges(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExchangesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByIntervalsCount orders the results by intervals count.
func ByIntervalsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIntervalsStep(), opts...)
	}
}

// ByIntervals orders the results by intervals terms.
func ByIntervals(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIntervalsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDividendsCount orders the results by dividends count.
func ByDividendsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDividendsStep(), opts...)
	}
}

// ByDividends orders the results by dividends terms.
func ByDividends(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDividendsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySplitsCount orders the results by splits count.
func BySplitsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSplitsStep(), opts...)
	}
}

// BySplits orders the results by splits terms.
func BySplits(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSplitsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFinancialsCount orders the results by financials count.
func ByFinancialsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFinancialsStep(), opts...)
	}
}

// ByFinancials orders the results by financials terms.
func ByFinancials(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFinancialsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newExchangesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExchangesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ExchangesTable, ExchangesPrimaryKey...),
	)
}
func newIntervalsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IntervalsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, IntervalsTable, IntervalsColumn),
	)
}
func newDividendsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DividendsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, DividendsTable, DividendsPrimaryKey...),
	)
}
func newSplitsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SplitsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SplitsTable, SplitsColumn),
	)
}
func newFinancialsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FinancialsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, FinancialsTable, FinancialsPrimaryKey...),
	)
}
