// Code generated by ent, DO NOT EDIT.

package financial

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the financial type in the database.
	Label = "financial"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeStock holds the string denoting the stock edge name in mutations.
	EdgeStock = "stock"
	// Table holds the table name of the financial in the database.
	Table = "financials"
	// StockTable is the table that holds the stock relation/edge. The primary key declared below.
	StockTable = "entity_financials"
	// StockInverseTable is the table name for the Entity entity.
	// It exists in this package in order to avoid circular dependency with the "entity" package.
	StockInverseTable = "entities"
)

// Columns holds all SQL columns for financial fields.
var Columns = []string{
	FieldID,
}

var (
	// StockPrimaryKey and StockColumn2 are the table columns denoting the
	// primary key for the stock relation (M2M).
	StockPrimaryKey = []string{"entity_id", "financial_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Financial queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStockCount orders the results by stock count.
func ByStockCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStockStep(), opts...)
	}
}

// ByStock orders the results by stock terms.
func ByStock(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStockStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newStockStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StockInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, StockTable, StockPrimaryKey...),
	)
}
