// Code generated by ent, DO NOT EDIT.

package bartimerange

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/nathanhack/sibyl/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldLTE(FieldID, id))
}

// Start applies equality check predicate on the "start" field. It's identical to StartEQ.
func Start(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldEQ(FieldStart, v))
}

// End applies equality check predicate on the "end" field. It's identical to EndEQ.
func End(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldEQ(FieldEnd, v))
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldEQ(FieldCount, v))
}

// IntervalID applies equality check predicate on the "interval_id" field. It's identical to IntervalIDEQ.
func IntervalID(v int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldEQ(FieldIntervalID, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldEQ(FieldUpdateTime, v))
}

// StartEQ applies the EQ predicate on the "start" field.
func StartEQ(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldEQ(FieldStart, v))
}

// StartNEQ applies the NEQ predicate on the "start" field.
func StartNEQ(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNEQ(FieldStart, v))
}

// StartIn applies the In predicate on the "start" field.
func StartIn(vs ...time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldIn(FieldStart, vs...))
}

// StartNotIn applies the NotIn predicate on the "start" field.
func StartNotIn(vs ...time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNotIn(FieldStart, vs...))
}

// StartGT applies the GT predicate on the "start" field.
func StartGT(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldGT(FieldStart, v))
}

// StartGTE applies the GTE predicate on the "start" field.
func StartGTE(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldGTE(FieldStart, v))
}

// StartLT applies the LT predicate on the "start" field.
func StartLT(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldLT(FieldStart, v))
}

// StartLTE applies the LTE predicate on the "start" field.
func StartLTE(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldLTE(FieldStart, v))
}

// EndEQ applies the EQ predicate on the "end" field.
func EndEQ(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldEQ(FieldEnd, v))
}

// EndNEQ applies the NEQ predicate on the "end" field.
func EndNEQ(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNEQ(FieldEnd, v))
}

// EndIn applies the In predicate on the "end" field.
func EndIn(vs ...time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldIn(FieldEnd, vs...))
}

// EndNotIn applies the NotIn predicate on the "end" field.
func EndNotIn(vs ...time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNotIn(FieldEnd, vs...))
}

// EndGT applies the GT predicate on the "end" field.
func EndGT(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldGT(FieldEnd, v))
}

// EndGTE applies the GTE predicate on the "end" field.
func EndGTE(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldGTE(FieldEnd, v))
}

// EndLT applies the LT predicate on the "end" field.
func EndLT(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldLT(FieldEnd, v))
}

// EndLTE applies the LTE predicate on the "end" field.
func EndLTE(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldLTE(FieldEnd, v))
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldEQ(FieldCount, v))
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNEQ(FieldCount, v))
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldIn(FieldCount, vs...))
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNotIn(FieldCount, vs...))
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldGT(FieldCount, v))
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldGTE(FieldCount, v))
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldLT(FieldCount, v))
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldLTE(FieldCount, v))
}

// IntervalIDEQ applies the EQ predicate on the "interval_id" field.
func IntervalIDEQ(v int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldEQ(FieldIntervalID, v))
}

// IntervalIDNEQ applies the NEQ predicate on the "interval_id" field.
func IntervalIDNEQ(v int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNEQ(FieldIntervalID, v))
}

// IntervalIDIn applies the In predicate on the "interval_id" field.
func IntervalIDIn(vs ...int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldIn(FieldIntervalID, vs...))
}

// IntervalIDNotIn applies the NotIn predicate on the "interval_id" field.
func IntervalIDNotIn(vs ...int) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNotIn(FieldIntervalID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNotIn(FieldStatus, vs...))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.FieldLTE(FieldUpdateTime, v))
}

// HasInterval applies the HasEdge predicate on the "interval" edge.
func HasInterval() predicate.BarTimeRange {
	return predicate.BarTimeRange(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IntervalTable, IntervalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIntervalWith applies the HasEdge predicate on the "interval" edge with a given conditions (other predicates).
func HasIntervalWith(preds ...predicate.Interval) predicate.BarTimeRange {
	return predicate.BarTimeRange(func(s *sql.Selector) {
		step := newIntervalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.BarTimeRange {
	return predicate.BarTimeRange(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.BarGroup) predicate.BarTimeRange {
	return predicate.BarTimeRange(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BarTimeRange) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BarTimeRange) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BarTimeRange) predicate.BarTimeRange {
	return predicate.BarTimeRange(sql.NotPredicates(p))
}
